import * as F from './finance.mjs';
const $=s=>document.querySelector(s);
const money=(n,d=2)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:d,minimumFractionDigits:d}).format(n);
const num=(n,d=2)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n);
const pct=n=>num(n*100,2)+'%';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const frac=(a,b)=>`<span class="fraction"><span>${a}</span><span>${b}</span></span>`;
const toolNames={tvm:'Time value',savings:'Savings',wacc:'WACC',dcf:'DCF valuation',bond:'Bonds',hamada:'Beta',options:'Options',mm:'Capital structure',dupont:'DuPont',fcf:'Free cash flow'};
const sidebar=$('.sidebar'),menuToggle=$('#menu-toggle'),mobileNav=matchMedia('(max-width:760px)');
function setMenu(open,{restoreFocus=false}={}){const shown=mobileNav.matches&&open;sidebar.classList.toggle('open',shown);sidebar.inert=mobileNav.matches&&!shown;menuToggle.setAttribute('aria-expanded',String(shown));if(restoreFocus&&mobileNav.matches)menuToggle.focus();}
mobileNav.addEventListener('change',()=>setMenu(false));setMenu(false);
const initial={payment:1000,rate:8,periods:10,first:1,growth:0,pattern:'level',target:'pv'};
let values={...initial},selectedYear=0,currentPreset='';
const presets={income:{label:'Steady income',values:initial},business:{label:'Growing business',values:{...initial,payment:450000,rate:10.96,periods:10,growth:2.87,pattern:'growing'}},saving:{label:'Save for later',values:{...initial,payment:20000,rate:9.8,periods:7,target:'fv'}},deferred:{label:'Wait for payments',values:{...initial,payment:7000,rate:11.1,periods:16,first:3}}};
function field(key,label,value,{unit='',step='any',min='',max='',help='',options=null}={}){return`<div class="field"><label for="${key}">${label}<span class="unit">${unit}</span></label>${options?`<select id="${key}" name="${key}">${options.map(([v,l])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${l}</option>`).join('')}</select>`:`<input id="${key}" name="${key}" type="number" value="${value}" step="${step}" ${min!==''?`min="${min}"`:''} ${max!==''?`max="${max}"`:''} required>`}${help?`<small>${help}</small>`:''}</div>`;}
function intro(title,description,asideTitle='Timing comes first.',aside='Choose a cash flow. Give it a date. Change the rate. The timeline shows you why the answer moves.'){return`<section class="intro"><div><h1>${title}</h1><p>${description}</p></div><div class="intro-aside"><span class="mini-label">Learn by changing things</span><strong>${asideTitle}</strong><p>${aside}</p></div></section>`;}
function rail(active='tvm'){return`<div class="tool-rail" aria-label="Finance calculators">${Object.entries(toolNames).map(([id,name],i)=>`<button data-tool="${id}" class="${id===active?'active':''}" aria-pressed="${id===active}"><span class="tool-num">${String(i+1).padStart(2,'0')}</span>${name}</button>`).join('')}</div>`;}
function shell(title,symbol,form,{dense=false,presetsHTML=''}={}){return`<section class="workspace ${dense?'input-dense':''}"><div class="workspace-head"><div class="workspace-title"><span class="workspace-symbol" aria-hidden="true">${symbol}</span><h2>${title}</h2></div><span class="live-label">Live calculation</span></div><div class="workspace-grid"><div class="controls"><form id="calculator">${form}<button class="reset-button" type="button" id="reset">↺ Reset example</button><p class="form-footer">Illustrative inputs. Change any value to explore.</p></form></div><div class="results" id="results"></div></div>${presetsHTML}</section>`;}
function steps(items){return`<section class="walkthrough"><h2>Follow the money.</h2>${items.map(([h,p],i)=>`<div class="step"><span class="step-number">${i+1}</span><div><h3>${h}</h3><p>${p}</p></div></div>`).join('')}</section>`;}
function resultTop(label,value,unit='',pill=''){return`<div class="result-top"><div><p class="result-label">${label}</p><div class="result-number" role="status" aria-live="polite">${value}</div><p class="result-unit">${unit}</p></div>${pill?`<span class="result-pill">${pill}</span>`:''}</div>`;}
function metrics(items){return`<div class="metric-row">${items.map(([l,v])=>`<div><span>${l}</span><strong>${v}</strong></div>`).join('')}</div>`;}
function chart(rows,key='pv'){
  const all=rows,limit=20;rows=all.length>limit?Array.from({length:limit},(_,i)=>all[Math.round(i*(all.length-1)/(limit-1))]):all;
  const largest=Math.max(...rows.flatMap(r=>[Math.abs(r.cash),Math.abs(r[key]??r.pv)]),.01);
  return`<div class="chart-title">${key==='pv'?'The same money. Two different dates.':'Watch the deposits accumulate.'}<div class="legend"><span>Payment</span><span>${key==='pv'?'Value today':'Future value'}</span></div></div><div class="cash-chart" role="group" aria-label="Payment amounts compared with their ${key==='pv'?'present':'future'} values">${rows.map(r=>{const index=all.indexOf(r);return`<button class="cash-column ${selectedYear===index?'selected':''}" data-year="${index}" aria-label="Year ${r.time}: payment ${money(r.cash)}, ${key==='pv'?'present':'future'} value ${money(r[key]??r.pv)}"><span class="chart-tooltip">${money(r[key]??r.pv,0)}</span><span class="bars"><span class="bar ${r.cash<0?'negative':''}" style="--bar-height:${Math.abs(r.cash)/largest*100}%"></span><span class="bar pv ${(r[key]??r.pv)<0?'negative':''}" style="--bar-height:${Math.abs(r[key]??r.pv)/largest*100}%"></span></span><span class="year">${num(r.time,1)}</span></button>`;}).join('')}</div><div class="chart-bottom"><span>Year of payment${all.length>limit?` · showing ${limit} of ${all.length}`:''}</span><span>Select a payment to inspect it</span></div><div id="year-detail" class="year-detail"></div>`;
}
function cashTable(rows,key='pv'){return`<details class="data-details"><summary>Inspect every cash flow</summary><div class="table-scroll"><table class="data-table"><thead><tr><th scope="col">Year</th><th scope="col">Payment</th><th scope="col">${key==='pv'?'Value today':'Future value'}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${num(r.time)}</td><td>${money(r.cash)}</td><td>${money(r[key]??r.pv)}</td></tr>`).join('')}</tbody></table></div></details>`;}
function tvmForm(){const v=values;return`<p class="section-hint">Put your cash flows on the timeline.</p>${field('pattern','Payment pattern',v.pattern,{options:[['level','Equal payments'],['growing','Growing payments'],['perpetuity','Payments forever']]})}${field('payment','First payment',v.payment,{unit:'$'})}${field('rate','Discount / interest rate',v.rate,{unit:'% per year',step:0.1,min:-99,help:'An effective annual rate; payments are annual.'})}${v.pattern!=='perpetuity'?field('periods','Number of payments',v.periods,{unit:'annual',step:1,min:1,max:1000}):''}${field('first','First payment arrives',v.first,{unit:'year',step:1,min:0,help:'0 = today · 1 = next year · 3 = in three years'})}${v.pattern!=='level'?field('growth','Payment growth',v.growth,{unit:'% per year',step:.1,min:-99}):''}${v.pattern!=='perpetuity'?field('target','Find the value',v.target,{options:[['pv','Today (present value)'],['fv','At the last payment (future value)']]}):''}`;}
function tvmPage(){
  $('#main').innerHTML=intro('See what time<br>does to money.','A dollar today and a dollar tomorrow are not the same thing. Put that idea to work.')+rail()+shell('Cash-flow playground','↗',tvmForm(),{presetsHTML:`<div class="preset-strip"><span>Try a real question</span>${Object.entries(presets).map(([k,p])=>`<button data-preset="${k}" class="${currentPreset===k?'active':''}">${p.label}</button>`).join('')}</div>`})+`<div class="below-grid" id="tvm-below"></div><div class="section-row"><h2>Make your next connection.</h2><a href="#concepts">Explore the concept atlas ↗</a></div><div class="next-topics"><a class="topic-link" href="#concept/tvm"><div><span>The foundation</span><strong>Why discounting works</strong></div><span class="arrow">↗</span></a><a class="topic-link" href="#lab/bond"><div><span>The next application</span><strong>A bond is a cash-flow timeline</strong></div><span class="arrow">↗</span></a><a class="topic-link" href="#lab/dcf"><div><span>The bigger picture</span><strong>Put a value on a business</strong></div><span class="arrow">↗</span></a></div>`;
  bindForm(tvmUpdate,()=>{values={...initial};currentPreset='';tvmPage();});
  $('#pattern').addEventListener('change',()=>{values={...values,...readForm()};selectedYear=0;tvmPage();});
  document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{values={...presets[b.dataset.preset].values};selectedYear=0;currentPreset=b.dataset.preset;tvmPage();}));
  bindRail();tvmUpdate();
}
function readForm(){return Object.fromEntries([...new FormData($('#calculator'))].map(([k,v])=>[k,['pattern','target','solve','type','position','timing'].includes(k)?v:v.trim()===''?NaN:Number(v)]));}
function bindForm(update,reset){$('#calculator').addEventListener('submit',e=>e.preventDefault());$('#calculator').addEventListener('input',update);$('#reset').addEventListener('click',reset);}
function showError(e){$('#results').innerHTML=`<div class="error-box" role="alert"><h3>Let’s check those inputs.</h3><p>${esc(e.message)}</p></div>`;}
function bindRail(){document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{location.hash=`lab/${b.dataset.tool}`;}));}
function inspectChart(rows,key){const select=i=>{selectedYear=i;const r=rows[i];document.querySelectorAll('[data-year]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.year)===i));$('#year-detail').innerHTML=`<span><strong>Year ${num(r.time)}:</strong> ${money(r.cash)} ${key==='pv'?'is worth':'grows to'} <strong>${money(r[key]??r.pv)}</strong> ${key==='pv'?'today':'at the last payment'}.</span>`;};document.querySelectorAll('[data-year]').forEach(b=>b.addEventListener('click',()=>select(Number(b.dataset.year))));select(Math.min(selectedYear,rows.length-1));}
function tvmUpdate(){
  const v=values={...values,...readForm()};try{
    const r=v.rate/100,g=v.pattern==='level'?0:v.growth/100;
    if(v.pattern==='perpetuity'){
      const pv=F.perpetuity({payment:v.payment,rate:r,growth:g,first:v.first});
      $('#results').innerHTML=resultTop('Present value',money(pv),'An infinite stream, valued today.','Infinite horizon')+metrics([['First payment',`Year ${v.first}`],['Annual growth',pct(g)],['Discount rate',pct(r)]])+`<div class="equation">PV = ${frac('C₁','r − g')} × (1 + r)<sup>1 − first year</sup><small>The first payment is C₁, wherever it falls on the timeline.</small></div><p class="result-explainer">There is no last payment, so there is no finite future value. Each payment may grow, but it must shrink <em>after discounting</em>: the discount rate must exceed the growth rate.</p><div class="callout">As growth approaches the discount rate from below, value becomes extremely sensitive. An infinite-horizon model is an assumption, not a promise.</div>`;
    }else{
      const a=F.cashFlowSeries({payment:v.payment,rate:r,growth:g,periods:v.periods,first:v.first}),key=v.target;
      const delta=key==='pv'?a.total-a.pv:a.fv-a.total;
      $('#results').innerHTML=resultTop(key==='pv'?'Present value':'Future value',money(a[key]),key==='pv'?'What this entire stream is worth today.':`Value immediately after the year-${a.end} payment.`,v.first===0?'First payment today':v.first>1?'Deferred payments':'Annual payments')+metrics([['Total payments',money(a.total,0)],[key==='pv'?'Discounting difference':'Interest earned',money(delta,0)],['Payment window',`Years ${v.first}–${a.end}`]])+chart(a.rows,key)+`<p class="result-explainer">${key==='pv'?`You receive <strong>${money(a.total,0)}</strong> across ${v.periods} payments. Their equivalent value today is <strong>${money(a.pv)}</strong>. ${r>0?'Later dollars contribute less because you wait longer.':r===0?'At a zero rate, time creates no discount.':'A negative discount rate makes later receipts worth more today.'}`:`The first deposit earns interest for <strong>${v.periods-1} years</strong>. The last deposit earns no interest yet. Adding all the accumulated deposits gives <strong>${money(a.fv)}</strong>.`}</p>`+cashTable(a.rows,key);
      inspectChart(a.rows,key);
    }
    const end=v.first+(v.periods||1)-1;
    $('#tvm-below').innerHTML=steps([['Place the payments.',`The first ${money(v.payment,0)} arrives in year ${v.first}${v.pattern==='perpetuity'?' and payments continue forever':`; the final payment arrives in year ${end}`}. ${v.first===0?'Today’s payment needs no discount.':''}`],['Move each amount to the same date.',v.target==='fv'&&v.pattern!=='perpetuity'?`Compound each deposit forward to year ${end}. Use one exponent for each deposit’s waiting time.`:'Divide each future payment by (1 + r) raised to its own year. Growing payments get larger before they are discounted.'],['Add the values, not the dates.','Once every payment is expressed at one common date, add them. The annuity formula is a shortcut for this sum.']])+`<aside class="connection"><h2>${v.first>1?'Why value it one year earlier?':'Change the rate. Watch the bars.'}</h2><p>${v.first>1?`The annuity shortcut values the stream in <strong>year ${v.first-1}</strong>, one year before its first payment. Discount that subtotal another ${v.first-1} years to today. The direct timeline above does both steps at once.`:'The orange bars are the actual payments. The blue bars show their value at your chosen date. A higher discount rate makes the present-value bars shorter. The payments themselves do not change.'}</p><a class="text-link" href="#concept/tvm">Get the intuition <span>↗</span></a><span class="connection-mark" aria-hidden="true">(1+r)ᵗ</span></aside>`;
  }catch(e){showError(e);}
}
async function render(){const hash=location.hash.slice(1)||'lab',parts=hash.split('/'),view=parts[0];document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===(view==='concept'?'concepts':view)));setMenu(false);
  if(view==='lab'&&(!parts[1]||parts[1]==='tvm')){$('#breadcrumb').innerHTML='The playground <span>/</span> Time value of money';tvmPage();}
  else{const more=await import('./library.mjs');await more.renderPage({view,id:parts[1],helpers:{F,$,money,num,pct,esc,frac,field,intro,rail,shell,steps,resultTop,metrics,chart,cashTable,bindForm,readForm,showError,bindRail,inspectChart}});}document.title=`${$('#breadcrumb').textContent.trim()} — Corpo Finance Lab`;
}
menuToggle.addEventListener('click',()=>setMenu(!sidebar.classList.contains('open')));
window.addEventListener('hashchange',async()=>{await render();window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true});});
document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false,{restoreFocus:true});});
render();
