export const definitions={
 wacc:{title:'Every source has a cost.',description:'Find the required return behind the financing mix. Then watch the weights do their work.',name:'Cost-of-capital mixer',symbol:'◐',concept:'capital',defaults:{rf:4,beta:1.2,erp:5,debtRate:6,tax:25,equity:600,debt:300,preferred:100,preferredRate:7},fields:[['rf','Risk-free rate','%'],['beta','Equity beta','×'],['erp','Equity risk premium','%'],['debtRate','Pre-tax debt cost','%'],['tax','Corporate tax rate','%'],['equity','Market equity','currency m'],['debt','Market debt','currency m'],['preferred','Market preferred','currency m'],['preferredRate','Preferred return','%']],steps:[['Price each source.','Estimate the current required return for equity, debt, and preferred capital.'],['Weight by market value.','Divide each source by total market capital. The weights add to one.'],['Apply the tax adjustment once.','Only deductible debt interest gets the (1−T) adjustment in this model.']]},
 dcf:{title:'A business is a stream of cash.',description:'Connect today’s price to tomorrow’s operating cash flows. Test the story, not just the spreadsheet.',name:'Discounted cash-flow studio',symbol:'◈',concept:'valuation',defaults:{fcf:100,growth:5,optimistic:8,pessimistic:2,terminalGrowth:2,rate:9,n:5,debt:200,cash:50,senior:0,shares:10},fields:[['fcf','Last year’s FCFF','currency m'],['growth','Base forecast growth','%'],['optimistic','Higher-growth scenario','%'],['pessimistic','Lower-growth scenario','%'],['terminalGrowth','Perpetual growth','%'],['rate','WACC','%'],['n','Forecast horizon','years'],['debt','Debt','currency m'],['cash','Excess / nonoperating cash','currency m'],['senior','Other senior claims','currency m'],['shares','Diluted shares','millions']],steps:[['Forecast operating cash flow.','Start with historical FCFF and state the growth assumption. This constant-growth forecast is deliberately simplified.'],['Value the continuing business.','Terminal value uses next year’s cash flow and is measured at the end of the forecast horizon.'],['Bridge to common equity.','Subtract debt and other senior claims, add nonoperating cash, then divide by diluted shares.']]},
 bond:{title:'Same promise. Different price.',description:'Move the yield and see a bond reprice. Inspect the coupons, principal, and timing behind the result.',name:'Bond pricing bench',symbol:'≋',concept:'securities',defaults:{solve:'price',face:1000,coupon:5,yield:6,years:5,frequency:2,price:950,callPrice:1020,callYears:3},fields:[['solve','Solve for','',[['price','Price from yield'],['ytm','Yield from price']]],['face','Face value','$'],['coupon','Annual coupon rate','%'],['yield','Nominal annual yield','%'],['price','Market price','$'],['years','Years to maturity','years'],['frequency','Coupons per year','',[[1,'Annual'],[2,'Semiannual'],[4,'Quarterly']]],['callPrice','Optional call price','$'],['callYears','Optional first call date','years']],steps:[['Write the bond’s payments.','Each coupon is face value × annual coupon rate ÷ coupons per year. Add principal to the final payment.'],['Use the periodic yield.','Divide the nominal annual yield by coupon frequency. The schedule must contain a whole number of coupon periods.'],['Discount and sum.','Price is the sum of discounted coupons and principal. Solving for yield reverses this process.']]},
 hamada:{title:'Separate business risk from debt.',description:'Unlever a comparable’s beta. Rebuild it for a different capital structure.',name:'Beta translator',symbol:'β',concept:'leverage',defaults:{beta:1.2,tax:25,de:.5,targetDe:1,rf:4,erp:5},fields:[['beta','Comparable equity beta','×'],['tax','Tax rate','%'],['de','Comparable market D/E','ratio'],['targetDe','Target market D/E','ratio'],['rf','Risk-free rate','%'],['erp','Equity risk premium','%']],steps:[['Remove comparable leverage.','Divide equity beta by 1 + (1−T)D/E to estimate unlevered beta.'],['Apply target leverage.','Multiply the unlevered beta by the target leverage factor.'],['Translate risk into a return.','Use target equity beta in CAPM with a currency-consistent risk-free rate and equity risk premium.']]},
 options:{title:'Find the shape of the payoff.',description:'Long or short. Call or put. Separate exercise value from actual profit.',name:'Option payoff studio',symbol:'⌁',concept:'options',defaults:{type:'call',position:'long',strike:100,premium:7,spot:120},fields:[['type','Option type','',[['call','Call · right to buy'],['put','Put · right to sell']]],['position','Position','',[['long','Long · buy the option'],['short','Short · sell the option']]],['strike','Strike price','$ / unit'],['premium','Premium paid / received','$ / unit'],['spot','Price at expiration','$ / unit']],steps:[['Check exercise value.','A call benefits above the strike; a put benefits below it. The buyer can choose not to exercise.'],['Choose the side of the contract.','The seller’s payoff is the negative of the buyer’s payoff.'],['Include the premium.','Long profit subtracts the premium; short profit adds it. This diagram ignores fees and financing costs.']]},
 mm:{title:'Change the mix. Question the model.',description:'Isolate the tax benefit of debt, then introduce a cost of financial distress.',name:'Capital-structure experiment',symbol:'△',concept:'leverage',defaults:{unlevered:100,debt:40,tax:25,distress:.2},fields:[['unlevered','Unlevered firm value','currency m'],['debt','Debt','currency m'],['tax','Corporate tax rate','%'],['distress','Distress intensity λ','ratio']],steps:[['Start with operating value.','Unlevered value is the benchmark before adding financing effects.'],['Add the assumed tax benefit.','The simple tax shield is T×D. Set the tax rate to zero to recover the no-tax case.'],['Subtract a modeled cost.','Here distress cost is λD²/Vᵁ. This quadratic shape is an illustration, not an empirical estimate.']]},
 dupont:{title:'A return has a backstory.',description:'Is profitability coming from margins, asset efficiency, or leverage? Pull the ratio apart.',name:'DuPont decomposition',symbol:'×',concept:'statements',defaults:{income:20,sales:200,assets:100,equity:50},fields:[['income','Net income','currency m'],['sales','Revenue','currency m'],['assets','Average total assets','currency m'],['equity','Average common equity','currency m']],steps:[['Margin: what do you keep?','Net income divided by sales measures accounting profit per unit of revenue.'],['Turnover: how hard do assets work?','Sales divided by average assets measures revenue per unit of asset investment.'],['Leverage: who financed the assets?','Average assets divided by average equity captures financial leverage. Multiply all three to recover ROE.']]},
 fcf:{title:'Profit isn’t the cash you can spend.',description:'Walk from operating earnings to cash available for all capital providers.',name:'Free-cash-flow builder',symbol:'⇢',concept:'valuation',defaults:{ebit:100,tax:25,da:10,capex:20,deltaNwc:5},fields:[['ebit','Operating profit · EBIT','currency m'],['tax','Cash tax rate','%'],['da','Depreciation & amortization','currency m'],['capex','Capital expenditure','currency m'],['deltaNwc','Increase in operating NWC','currency m']],steps:[['Remove operating taxes.','NOPAT = EBIT×(1−T). For operating losses, this shortcut assumes tax benefits can be used immediately.'],['Undo noncash charges.','Add back depreciation and amortization, which reduced earnings but are not current cash payments.'],['Pay for reinvestment.','Subtract capital expenditure and the increase in operating working capital. A negative ΔNWC releases cash.']]},
 savings:{title:'Work backward from the goal.',description:'Find a starting balance, target balance, deposit, rate, or saving period using one consistent cash-flow equation.',name:'Lump sum & savings solver',symbol:'↗',concept:'tvm',defaults:{solve:'fv',pv:1000,fv:2000,pmt:100,rate:8,n:10,frequency:1,timing:'end'},fields:[['solve','Solve for','',[['fv','Future balance'],['pv','Starting balance'],['pmt','Deposit per period'],['rate','Nominal annual rate'],['n','Saving period in years']]],['pv','Starting balance','$'],['fv','Target future balance','$'],['pmt','Deposit each period','$'],['rate','Nominal annual rate · APR','%'],['n','Saving period','years'],['frequency','Periods per year','',[[1,'Annual'],[2,'Semiannual'],[4,'Quarterly'],[12,'Monthly'],[365,'Daily']]],['timing','Deposit timing','',[['end','End of period'],['due','Beginning of period']]]],steps:[['Match the period.','Periodic rate = nominal APR ÷ periods per year. Number of periods = years × periods per year.'],['Use one savings identity.','Future balance = accumulated starting balance + accumulated deposits. All solve modes rearrange that identity.'],['Read the units.','Payments are per deposit period. Solved time is reported in years. Solved rate is nominal APR, with EAR shown separately.']]}
};

export function calculatorPage(id,H){
 const {$,F,field,intro,rail,shell,steps,resultTop,metrics,chart,cashTable,bindForm,readForm,showError,bindRail,inspectChart,money,num,pct,frac,esc}=H;
 const cfg=definitions[id];if(!cfg){location.hash='lab';return;}
 const moneyM=x=>money(x,2)+'m';
 function linePlot(series,{xTitle='Input',yTitle='Value',markers=[]}={}){
  const xs=series.flatMap(s=>s.points.map(p=>p[0])),ys=series.flatMap(s=>s.points.map(p=>p[1])).filter(Number.isFinite);
  const lo=Math.min(0,...ys),hi=Math.max(...ys,1),x0=Math.min(...xs),x1=Math.max(...xs),W=570,HH=220,L=54,R=20,T=14,B=35;
  const x=v=>L+(v-x0)/(x1-x0||1)*(W-L-R),y=v=>T+(hi-v)/(hi-lo||1)*(HH-T-B);
  return`<div class="plot-wrap"><svg class="plot-svg" viewBox="0 0 ${W} ${HH}" role="img" aria-label="${esc(yTitle)} versus ${esc(xTitle)}"><title>${esc(yTitle)} versus ${esc(xTitle)}</title>${[0,.25,.5,.75,1].map(t=>{const v=lo+(hi-lo)*t;return`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#e5e8f0"/><text x="${L-9}" y="${y(v)+4}" text-anchor="end">${num(v,0)}</text>`;}).join('')}<line x1="${L}" x2="${W-R}" y1="${y(0)}" y2="${y(0)}" stroke="#bfc7dc"/>${series.map((s,i)=>`<polyline points="${s.points.map(p=>`${x(p[0])},${y(p[1])}`).join(' ')}" stroke="${s.color||['#4e62d8','#fa9575','#98a5c4'][i]}" stroke-width="3" fill="none"/>`).join('')}${markers.map(m=>`<circle cx="${x(m[0])}" cy="${y(m[1])}" r="5" fill="#20294b" stroke="white" stroke-width="2"/>`).join('')}<text x="${L}" y="${HH-13}">${num(x0,0)}</text><text x="${W-R}" y="${HH-13}" text-anchor="end">${num(x1,0)}</text><text x="${W/2}" y="${HH-5}" text-anchor="middle">${esc(xTitle)}</text></svg><div class="legend">${series.map((s,i)=>`<span style="--legend-color:${s.color||['#4e62d8','#fa9575','#98a5c4'][i]}">${s.label}</span>`).join('')}</div></div>`;
 }
 function miniBars(rows){const max=Math.max(...rows.map(r=>Math.abs(r.value)),.001);return`<div class="mini-bars">${rows.map(r=>`<div class="mini-bar-line"><span>${r.label}</span><div class="mini-bar-track"><i style="--w:${Math.abs(r.value)/max*100}%"></i></div><strong>${r.display??num(r.value)}</strong></div>`).join('')}</div>`;}
 const equations={wacc:`WACC = ${frac('E','V')}rₑ + ${frac('D','V')}r𝒹(1−T) + ${frac('P','V')}rₚ`,dcf:`EV = ∑ ${frac('FCFFₜ','(1+WACC)<sup>t</sup>')} + ${frac('FCFFₙ₊₁ / (WACC−g∞)','(1+WACC)<sup>n</sup>')}`,bond:`P = ∑ ${frac('Coupon','(1+y/m)<sup>t</sup>')} + ${frac('Face value','(1+y/m)<sup>N</sup>')}`,hamada:`βᵁ = ${frac('βᴸ','1+(1−T)D/E')} &nbsp; ; &nbsp; βᴸ,target = βᵁ[1+(1−T)D/E<sub>target</sub>]`,options:'Long call profit = max(Sₜ − K, 0) − Premium<br>Long put profit = max(K − Sₜ, 0) − Premium',mm:`Vᴸ = Vᵁ + TD − λ ${frac('D²','Vᵁ')}`,dupont:`ROE = ${frac('Net income','Sales')} × ${frac('Sales','Average assets')} × ${frac('Average assets','Average equity')}`,fcf:'FCFF = EBIT(1−T) + D&A − CapEx − ΔOperating NWC',savings:`FV = PV(1+r)<sup>N</sup> + PMT × ${frac('(1+r)<sup>N</sup>−1','r')} × Timing factor`};
 const assumptions={wacc:'Market-value weights. The debt tax shield assumes usable deductions. Use a rate appropriate for the cash-flow risk; a parent company’s WACC is not universal.',dcf:'End-of-year unlevered cash flows. Constant forecast growth is a teaching simplification. Terminal growth must be sustainable and below WACC. Senior claims include preferred stock when relevant.',bond:'Regular coupon dates, valuation on a coupon date, and no default. Yield is nominal annual with the selected compounding frequency. No accrued interest or irregular stub periods.',hamada:'Comparable operating risk, a shared tax rate, and negligible debt beta. A change in debt policy may require a more detailed model.',options:'Per underlying unit, at expiration. Excludes fees and financing costs. This is a payoff diagram, not a model of an option’s price before expiration.',mm:'The quadratic distress term is an illustrative trade-off model, not an M&M theorem. The plotted debt range is 0≤D≤Vᵁ.',dupont:'Use period net income and sales with average assets and average equity. Positive equity is required for the standard interpretation.',fcf:'Consistent operating scope. Positive CapEx is spending; negative ΔNWC releases cash. EBIT(1−T) assumes immediate use of tax losses if EBIT is negative.',savings:'Positive PMT means money added to savings. The starting-balance solve subtracts the value of deposits from the target. Negative outputs remain negative. Beginning deposits use timing factor 1+r.'};
 let state={...cfg.defaults};
 function render(){
  $('#breadcrumb').innerHTML=`The playground <span>/</span> ${cfg.name}`;
  const form='<p class="section-hint">'+(id==='dcf'?'All company amounts in millions. Price is per share.':id==='savings'?'Leave the solved variable alone; its input is ignored.':'Change the assumptions. Inspect the result.')+'</p>'+cfg.fields.map(([key,label,unit,options])=>field(key,label,state[key],{unit,options,step:['n','frequency'].includes(key)?1:'any'})).join('');
  $('#main').innerHTML=intro(cfg.title,cfg.description,'Make one change at a time.','Predict the direction first. Then change an input and inspect what the model actually says.')+rail(id)+shell(cfg.name,cfg.symbol,form,{dense:true})+`<div class="below-grid">${steps(cfg.steps)}<aside class="connection"><h2>Know the model’s limits.</h2><p>${assumptions[id]}</p><a class="text-link" href="#concept/${cfg.concept}">Read the concept <span>↗</span></a></aside></div>${id==='savings'?'<a class="text-link" href="#lab/tvm">Back to the cash-flow playground ↗</a>':''}${id==='fcf'?workingCapitalForm():''}`;
  bindForm(update,()=>{state={...cfg.defaults};render();});bindRail();
  if(id==='bond'||id==='savings'){$('#solve').addEventListener('change',()=>{state={...state,...readForm()};setIgnored();});setIgnored();}
  if(id==='fcf')bindCapital();update();
 }
 function setIgnored(){const solve=$('#solve').value;const ignore=id==='bond'?(solve==='price'?'price':'yield'):(solve==='rate'?'rate':solve);cfg.fields.forEach(([k])=>{const input=$('#'+k);if(input&&input.tagName==='INPUT'){input.disabled=k===ignore;input.closest('.field').classList.toggle('ignored-field',k===ignore);}});}
 function update(){state={...state,...readForm()};const v={...state};try{
   let output='',explain='';
   if(id==='wacc'){
    const a=F.wacc({...v,rf:v.rf/100,erp:v.erp/100,debtRate:v.debtRate/100,tax:v.tax/100,preferredRate:v.preferredRate/100});
    output=resultTop('Weighted average cost of capital',pct(a.value),'Annual required return on the modeled operating cash flows.')+metrics([['Equity cost',pct(a.equityRate)],['After-tax debt cost',pct(a.afterTaxDebt)]])+miniBars(a.rows.map(r=>({label:r.label,value:r.weight,display:pct(r.weight)})))+`<div class="table-scroll"><table class="data-table"><caption class="sr-only">Cost and weighted contribution by capital source</caption><thead><tr><th scope="col">Capital source</th><th scope="col">Weight</th><th scope="col">Cost</th><th scope="col">Contribution</th></tr></thead><tbody>${a.rows.map(r=>`<tr><th scope="row">${r.label}</th><td>${pct(r.weight)}</td><td>${pct(r.cost)}</td><td>${pct(r.weight*r.cost)}</td></tr>`).join('')}</tbody></table></div>`;
    explain=`Equity costs ${pct(a.equityRate)}. Debt costs ${pct(a.afterTaxDebt)} after the modeled tax shield. Weight the sources by market value to get <strong>${pct(a.value)}</strong>.`;
   }else if(id==='dcf'){
    if(v.senior<0)throw Error('Other senior claims must be zero or positive.');if(v.optimistic<v.growth||v.pessimistic>v.growth)throw Error('Order forecast growth: lower scenario ≤ base ≤ higher scenario.');
    const calc=g=>F.dcf({...v,growth:g/100,terminalGrowth:v.terminalGrowth/100,rate:v.rate/100,debt:v.debt+v.senior});
    const a=calc(v.growth),scenarios=[['Lower growth',calc(v.pessimistic)],['Base case',a],['Higher growth',calc(v.optimistic)]];
    output=resultTop('Base-case common equity value / share',money(a.price),'A model-implied value, not a prediction of market price.')+metrics([['Enterprise value',moneyM(a.ev)],['Common equity',moneyM(a.equity)],['Terminal share of EV',a.terminalShare===null?'Undefined':pct(a.terminalShare)]])+chart(a.rows)+`<div class="table-scroll"><table class="data-table scenario-table"><caption class="sr-only">DCF values by forecast-growth scenario</caption><thead><tr><th scope="col">Scenario</th><th scope="col">PV forecast</th><th scope="col">PV terminal</th><th scope="col">Per share</th></tr></thead><tbody>${scenarios.map(([label,b])=>`<tr class="${label==='Base case'?'base':''}"><th scope="row">${label}</th><td>${moneyM(b.pvFlows)}</td><td>${moneyM(b.pvTerminal)}</td><td>${money(b.price)}</td></tr>`).join('')}</tbody></table></div><details class="data-details"><summary>WACC × terminal-growth sensitivity</summary><div class="table-scroll"><table class="data-table"><caption class="sr-only">Per-share value by WACC and perpetual-growth assumptions</caption><thead><tr><th scope="col">WACC / g∞</th>${[-.5,0,.5].map(d=>`<th scope="col">${num(v.terminalGrowth+d)}%</th>`).join('')}</tr></thead><tbody>${[-1,0,1].map(dr=>`<tr><th scope="row">${num(v.rate+dr)}%</th>${[-.5,0,.5].map(dg=>{try{return`<td>${money(F.dcf({...v,debt:v.debt+v.senior,growth:v.growth/100,rate:(v.rate+dr)/100,terminalGrowth:(v.terminalGrowth+dg)/100}).price)}</td>`;}catch{return'<td>Not valid</td>';}}).join('')}</tr>`).join('')}</tbody></table></div></details>`;
    explain=`Forecast cash flows contribute ${moneyM(a.pvFlows)}; the continuing business contributes ${moneyM(a.pvTerminal)} today. ${a.equity<0?'<strong>The simplified bridge produces negative common equity; common stock has limited liability, so treat this as a distress/model warning, not a literal negative trading price.</strong>':'Vary the assumptions before interpreting the price.'}`;
   }else if(id==='bond'){
    const args={...v,coupon:v.coupon/100,yield:v.yield/100};let y=args.yield;if(v.solve==='ytm')y=F.bondYield(args);
    const a=F.bond({...args,yield:y}),market=v.solve==='price'?a.price:v.price;
    let call='';if(v.callYears>0&&v.callPrice>0){if(v.callYears>v.years)throw Error('The call date cannot be after maturity.');const yc=F.bondYield({face:v.callPrice,coupon:v.face*(v.coupon/100)/v.callPrice,years:v.callYears,frequency:v.frequency,price:market});call=`<div class="callout">If called in year ${num(v.callYears)} at ${money(v.callPrice)}, yield to call is <strong>${pct(yc)}</strong> nominal annual. This assumes the stated call actually occurs.</div>`;}
    output=resultTop(v.solve==='price'?'Bond price':'Yield to maturity',v.solve==='price'?money(a.price):pct(y),v.solve==='price'?'Value on a coupon date, before accrued-interest adjustments.':'Nominal annual yield with the selected coupon frequency.')+metrics([['Coupon / period',money(a.couponPayment)],['Macaulay duration',num(a.duration,3)+' years'],['Modified duration',num(a.modifiedDuration,3)]])+chart(a.rows)+call+cashTable(a.rows);
    explain=`A yield of ${pct(y)} prices the cash flows at <strong>${money(a.price)}</strong>. ${y>args.coupon?'Yield exceeds the coupon rate, so the bond trades below par.':y<args.coupon?'Yield is below the coupon rate, so the bond trades above par.':'Yield matches the coupon rate, so the bond trades at par.'} Modified duration approximates the percentage price change for a small yield change.`;
   }else if(id==='hamada'){
    const a=F.hamada({...v,tax:v.tax/100}),equityRate=v.rf/100+a.relevered*v.erp/100;
    const points=Array.from({length:41},(_,i)=>{const d=i/10;return[d,F.hamada({...v,tax:v.tax/100,targetDe:d}).relevered];});
    output=resultTop('Target equity beta',num(a.relevered,3)+'×','Business risk, translated to the target financing mix.')+metrics([['Unlevered beta',num(a.unlevered,3)+'×'],['Comparable beta',num(v.beta,3)+'×'],['Target CAPM return',pct(equityRate)]])+linePlot([{label:'Target equity beta',points}],{xTitle:'Target market debt / equity',yTitle:'Equity beta'});
    explain=`First strip out the comparable’s leverage: βᵁ = <strong>${num(a.unlevered,3)}</strong>. Reapply target D/E of ${num(v.targetDe)} to get βᴸ = <strong>${num(a.relevered,3)}</strong>.`;
   }else if(id==='options'){
    const a=F.option(v),max=Math.max(v.strike*2,v.spot*1.3,1),points=Array.from({length:81},(_,i)=>{const spot=i/80*max;return[spot,F.option({...v,spot})];});
    output=resultTop('Profit at expiration',money(a.profit),'Per underlying unit, including the initial premium.')+metrics([['Exercise payoff',money(a.payoff)],['Break-even',a.breakEven===null?'Not attainable':money(a.breakEven)],['Position',v.position+' '+v.type]])+linePlot([{label:'Profit',color:'#4e62d8',points:points.map(([x,o])=>[x,o.profit])},{label:'Payoff',color:'#fa9575',points:points.map(([x,o])=>[x,o.payoff])}],{xTitle:'Underlying price at expiration ($)',yTitle:'Profit / payoff per unit ($)',markers:[[v.spot,a.profit]]});
    explain=`At an underlying price of ${money(v.spot)}, the ${v.position} ${v.type} payoff is ${money(a.payoff)}. ${v.position==='long'?'Subtract':'Add'} the ${money(v.premium)} premium to get <strong>${money(a.profit)}</strong> profit.${v.premium===0?' With zero premium, the out-of-the-money region also has zero profit; the strike is the boundary, not a unique zero-profit point.':''}`;
   }else if(id==='mm'){
    if(v.debt>v.unlevered)throw Error('For this constrained experiment, debt must not exceed unlevered firm value.');const args={...v,tax:v.tax/100},a=F.leverage(args),points=Array.from({length:61},(_,i)=>{const debt=i/60*v.unlevered;return[debt,F.leverage({...args,debt})];});
    const optimum=a.optimum===null?(v.tax>0?v.unlevered:null):Math.min(v.unlevered,Math.max(0,a.optimum));
    output=resultTop('Modeled levered firm value',moneyM(a.value),'Unlevered value + tax benefit − illustrative distress cost.')+metrics([['Tax shield',moneyM(a.shield)],['Distress cost',moneyM(a.cost)],['Best D in plotted range',optimum===null?'All debt levels tie':moneyM(optimum)]])+linePlot([{label:'With distress cost',color:'#4e62d8',points:points.map(([d,o])=>[d,o.value])},{label:'Tax shield only',color:'#fa9575',points:points.map(([d,o])=>[d,v.unlevered+args.tax*d])}],{xTitle:'Debt (currency millions)',yTitle:'Firm value (millions)',markers:[[v.debt,a.value]]});
    explain=`Debt adds ${moneyM(a.shield)} of modeled tax benefits and subtracts ${moneyM(a.cost)} of modeled distress costs. ${v.tax===0&&v.distress===0?'With both frictions removed, every financing mix has the same firm value.':'The “best” debt level is conditional on this assumed cost function and the plotted constraint.'}`;
   }else if(id==='dupont'){
    const a=F.dupont(v);output=resultTop('Return on equity',pct(a.roe),'Period net income divided by average common equity.')+metrics([['Profit margin',pct(a.margin)],['Asset turnover',num(a.turnover,3)+'×'],['Equity multiplier',num(a.multiplier,3)+'×']])+`<div class="dupont-flow"><div><span>Keep</span><strong>${pct(a.margin)}</strong><small>of every revenue dollar</small></div><b>×</b><div><span>Turn</span><strong>${num(a.turnover)}×</strong><small>assets into revenue</small></div><b>×</b><div><span>Finance</span><strong>${num(a.multiplier)}×</strong><small>assets relative to equity</small></div></div>`;
    explain=`${pct(a.margin)} × ${num(a.turnover)} × ${num(a.multiplier)} = <strong>${pct(a.roe)}</strong>. The identity always reconciles. The economic explanation requires comparing each driver, not celebrating the final ratio alone.`;
   }else if(id==='fcf'){
    const a=F.fcf({...v,tax:v.tax/100});output=resultTop('Free cash flow to the firm',moneyM(a.value),'Operating cash after taxes and reinvestment, before financing.')+metrics([['Operating profit',moneyM(v.ebit)],['NOPAT',moneyM(a.nopat)],['Net reinvestment',moneyM(v.capex+v.deltaNwc-v.da)]])+miniBars([...a.rows.map(r=>({...r,value:r.cash,display:moneyM(r.cash)})),{label:'FCFF',value:a.value,display:moneyM(a.value)}]);
    explain=`${moneyM(a.nopat)} after-tax operating profit + ${moneyM(v.da)} noncash charges − ${moneyM(v.capex)} capital spending − ${moneyM(v.deltaNwc)} operating working-capital investment = <strong>${moneyM(a.value)}</strong>. ${a.value<0?'Negative free cash flow can reflect investment, weak operations, or both.':''}`;
   }else if(id==='savings'){
    const r=v.rate/100/v.frequency,N=v.n*v.frequency,a=F.solveTVM({...v,n:N,rate:r,due:v.timing==='due'}),label={fv:'Future balance',pv:'Required starting balance',pmt:'Deposit per period',rate:'Required nominal annual rate',n:'Saving period'}[v.solve];
    const value=v.solve==='rate'?pct(a*v.frequency):v.solve==='n'?num(a/v.frequency,4)+' years':money(a);
    output=resultTop(label,value,'Positive deposits add to the starting balance.')+metrics(v.solve==='rate'?[['Periodic rate',pct(a)],['Effective annual rate',pct((1+a)**v.frequency-1)]]:v.solve==='n'?[['Total periods',num(a,4)],['Deposit frequency',num(v.frequency)+'/year']]:[['Periodic rate',pct(r)],['Total periods',num(N)],['Deposit timing',v.timing==='due'?'Beginning':'End']]);
    explain=`${v.solve==='n'?'The solved period may be fractional; actual scheduled deposits need a discrete final-payment convention.':v.solve==='rate'?'The rate solver supports nonnegative balances/deposits with a positive target and reports a bracketed solution.':'The solved input is ignored; all other inputs enter the same savings identity.'} ${v.timing==='due'?'Each beginning deposit earns one additional period of interest.':''}`;
   }
   $('#results').innerHTML=output+`<div class="equation">${equations[id]}</div><p class="result-explainer">${explain}</p>`;
   if(['dcf','bond'].includes(id)){const rows=id==='dcf'?F.dcf({...v,debt:v.debt+v.senior,growth:v.growth/100,terminalGrowth:v.terminalGrowth/100,rate:v.rate/100}).rows:F.bond({...v,coupon:v.coupon/100,yield:v.solve==='ytm'?F.bondYield({...v,coupon:v.coupon/100}):v.yield/100}).rows;inspectChart(rows,'pv');}
  }catch(e){showError(e);}
 }
 function workingCapitalForm(){const fs=[['currentAssets','Current assets',3000],['excessCash','Nonoperating cash / financial assets',400],['currentLiabilities','Current liabilities',1800],['shortDebt','Short-term financing debt',200],['priorAssets','Prior current assets',2700],['priorExcessCash','Prior nonoperating cash / financial assets',350],['priorLiabilities','Prior current liabilities',1700],['priorShortDebt','Prior short-term financing debt',180]];return`<section class="walkthrough" style="margin-top:24px"><h2>Build ΔOperating NWC from balances.</h2><p class="section-hint">All amounts in the same currency millions. Exclude financing items; keep required operating cash only if your convention includes it consistently.</p><form id="capital-form" class="capital-form">${fs.map(([k,l,val])=>field(k,l,val,{unit:'m'})).join('')}</form><div id="capital-result" class="callout"></div></section>`;}
 function bindCapital(){const refresh=()=>{try{const args=Object.fromEntries([...new FormData($('#capital-form'))].map(([k,x])=>[k,x===''?NaN:Number(x)])),a=F.operatingCapital(args);$('#capital-result').innerHTML=`Current operating NWC: <strong>${moneyM(a.current)}</strong> · Prior: <strong>${moneyM(a.prior)}</strong> · Increase: <strong>${moneyM(a.delta)}</strong><br><button type="button" class="primary-link" id="use-nwc">Use ${num(a.delta)} in the FCF builder</button>`;$('#use-nwc').addEventListener('click',()=>{$('#deltaNwc').value=a.delta;update();});}catch(e){$('#capital-result').textContent=e.message;}};$('#capital-form').addEventListener('input',refresh);$('#capital-form').addEventListener('submit',e=>e.preventDefault());refresh();}
 render();
}
