import {concepts,resources} from './content.mjs';
import {calculatorPage} from './calculators.mjs';
export async function renderPage({view,id,helpers:H}){
 const {$,F,money,num,pct}=H,main=$('#main');
 const header=(title,desc)=>`<section class="content-intro"><h1>${title}</h1><p>${desc}</p></section>`;
 const card=c=>`<a class="concept-card" href="#concept/${c.id}"><span class="concept-icon" aria-hidden="true">${c.icon}</span><h2>${c.title}</h2><p>${c.summary}</p><div class="concept-meta"><span>${c.level}</span><span>Explore ↗</span></div></a>`;
 const formula=f=>`<article class="formula-card"><h2>${f.name}</h2><div class="equation">${f.math}</div><p>${f.use}</p><p class="assumption"><strong>Before you use it:</strong> ${f.assumption}</p></article>`;
 if(view==='lab'){calculatorPage(id,H);return;}
 if(view==='concepts'){
  $('#breadcrumb').textContent='Concept atlas';
  main.innerHTML=header('Find the idea<br>behind the equation.','Start with the foundations or jump to what you need. Each topic connects intuition, a worked example, the formula, and the assumptions that make it valid.')+`<div class="choice-row" aria-label="Topic level"><button data-level="all" class="active" aria-pressed="true">All 13 topics</button><button data-level="core" aria-pressed="false">Core path</button><button data-level="extension" aria-pressed="false">Go deeper</button></div><div class="topic-grid" id="topic-grid">${concepts.map(card).join('')}</div>`;
  document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-level]').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-pressed',String(t===b));});$('#topic-grid').innerHTML=concepts.filter(c=>b.dataset.level==='all'||(b.dataset.level==='extension'?c.level==='Extension':c.level!=='Extension')).map(card).join('');}));
 }else if(view==='concept'){
  const c=concepts.find(x=>x.id===id);if(!c){location.hash='concepts';return;}
  $('#breadcrumb').innerHTML=`Concept atlas <span>/</span> ${c.title}`;
  main.innerHTML=`<a href="#concepts" class="return-link">← Back to the atlas</a><span class="level">${c.level}</span>`+header(c.title,c.summary)+`<div class="lesson-layout"><article class="lesson-body"><h2>The intuition</h2><p>${c.intuition}</p><h2>Build the idea</h2><ul>${c.points.map(p=>`<li>${p}</li>`).join('')}</ul><h2>Work through an example</h2><p>${c.example.question}</p><div class="equation">${c.example.working}</div><p><strong>${c.example.answer}</strong></p><h2>Put a formula to it</h2>${c.formulas.map(f=>`<section><h3>${f.name}</h3><div class="equation">${f.math}</div><p>${f.use}</p><div class="callout">${f.assumption}</div></section>`).join('')}<h2>Explain it back</h2><p>${c.prompt}</p><details class="data-details"><summary>What a strong explanation should connect</summary><p>${c.intuition} Then identify the assumption you would change and predict what happens to the result.</p></details></article><aside class="lesson-aside"><div><h3>Make it tangible.</h3><p>Change the numbers and trace the mechanism in the related calculator.</p><a class="primary-link" href="#lab/${c.tool}">Open the calculator <span>↗</span></a></div><div><h3>The common trap</h3><p>${c.pitfall}</p></div><div><h3>Keep connecting.</h3><a class="text-link" href="#concept/${c.next}">${concepts.find(x=>x.id===c.next)?.title} ↗</a></div></aside></div>`;
 }else if(view==='formulas'){
  $('#breadcrumb').textContent='Formula desk';
  main.innerHTML=header('A formula is a shortcut.<br>Know what it skips.','A reference you can use without losing the assumptions. Rates are decimals inside formulas; every rate must match its payment period.')+`<div class="field" style="max-width:420px;margin-bottom:25px"><label for="formula-topic">Jump to a topic</label><select id="formula-topic"><option value="all">All formulas</option>${concepts.map(c=>`<option value="${c.id}">${c.title}</option>`).join('')}</select></div><div class="formula-list" id="formula-list">${concepts.flatMap(c=>c.formulas).map(formula).join('')}</div><aside class="connection" style="margin-top:24px"><h2>Excel has a cash-flow sign convention.</h2><p>In PV(), FV(), PMT(), RATE(), and NPER(), cash you pay and cash you receive have opposite signs. For a savings target, a starting deposit and recurring deposits are negative cash flows while the future withdrawal is positive. In the lab’s savings solver, positive deposits mean additions to a balance; translate the signs when using Excel.</p><div class="equation">=FV(8%, 10, −100, −1000, 0)<small>10 end-of-year deposits of $100 plus $1,000 deposited today, earning 8% annually.</small></div><p>Excel’s NPV() starts discounting with its first listed cash flow one period away. Add the time-zero cash flow separately. Use XNPV()/XIRR() when dates are irregular.</p><a class="text-link" href="#lab/savings">Open the savings solver ↗</a></aside>`;
  $('#formula-topic').addEventListener('change',()=>{$('#formula-list').innerHTML=concepts.filter(c=>$('#formula-topic').value==='all'||c.id===$('#formula-topic').value).flatMap(c=>c.formulas).map(formula).join('');});
 }else if(view==='valuation'){
  $('#breadcrumb').textContent='Valuation guide';
  const op=F.fcf({ebit:100,tax:.25,da:10,capex:20,deltaNwc:5}),cap=F.wacc({rf:.04,beta:1.2,erp:.05,debtRate:.06,tax:.25,equity:600,debt:300,preferred:100,preferredRate:.07}),v=F.dcf({fcf:op.value,growth:.05,terminalGrowth:.02,rate:cap.value,n:5,debt:400,cash:50,shares:100});
  const guide=[
   ['Document the business.','Choose a company and a valuation date. Record your currency, financial units, forecast horizon, diluted share count, and data sources. Read the filings before forecasting.','The illustrative company below uses currency millions and 100 million shares. No market data or live recommendation is implied.','resources','Find primary sources'],
   ['Reconstruct operating cash flow.','Separate operations from financing. Normalize unusual items only with an explicit reason. Distinguish required operating cash from excess cash and reconcile reinvestment.','EBIT 100 × (1−25%) + D&A 10 − CapEx 20 − ΔNWC 5 = <strong>FCFF '+num(op.value)+'m</strong>.','lab/fcf','Build free cash flow'],
   ['Match risk and required return.','Use market or target capital weights. Estimate current marginal capital costs. Keep nominal/real treatment, currency, and cash-flow risk aligned.','Equity: 600m at 10%; debt: 300m at 6%; preferred: 100m at 7%; tax: 25%. <strong>WACC = '+pct(cap.value)+'</strong>.','lab/wacc','Build the cost of capital'],
   ['Forecast the operating story.','Explain revenue growth, margins, operating capital, and reinvestment. A growth rate is an assumption to defend. Forecast scenarios should represent coherent business stories.','For this teaching example only, grow prior FCFF of 60m by 5% annually for five years. <strong>PV of explicit cash flows = '+money(v.pvFlows)+'m</strong>.','lab/dcf','Explore the DCF model'],
   ['Close the horizon carefully.','A stable terminal stage still needs reinvestment to support growth. Use next year’s cash flow in the perpetuity, require g∞ below WACC, and discount terminal value from the end of the forecast.','At 2% terminal growth, <strong>PV of terminal value = '+money(v.pvTerminal)+'m</strong>; enterprise value = '+money(v.ev)+'m.','concept/valuation','Understand continuation value'],
   ['Bridge, stress-test, and explain.','Deduct debt and other senior claims. Add relevant nonoperating assets. Divide by diluted shares, then test WACC, terminal growth, operating assumptions, and scenario dependence.','('+num(v.ev)+' − debt 300 − preferred 100 + excess cash 50) / 100m shares = <strong>'+money(v.price)+' per share</strong>. Terminal value accounts for '+pct(v.terminalShare)+' of enterprise value.','lab/dcf','Test the sensitivity']
  ];
  main.innerHTML=header('Build a valuation<br>you can defend.','A reusable analytical sequence, from the first filing to the last sensitivity check. The numbers below form one continuous illustrative case.')+`<div class="guide-steps">${guide.map(([title,body,example,href,link],i)=>`<article class="guide-step"><span class="guide-number">${String(i+1).padStart(2,'0')}</span><div><h2>${title}</h2><p>${body}</p><div class="callout">${example}</div><a class="text-link" href="#${href}">${link} ↗</a></div></article>`).join('')}</div><aside class="connection" style="margin-top:24px"><h2>The final check</h2><p>Could someone reconstruct your answer from the stated assumptions? Can you explain the main value driver, the biggest uncertainty, and the change that would reverse your conclusion? A precise price without those answers is not a finished valuation.</p></aside>`;
 }else if(view==='resources'){
  $('#breadcrumb').textContent='Reading room';
  main.innerHTML=header('Go to the source.','A small reading shelf for the next layer of understanding. Use textbooks for foundations, lectures for mechanisms, and primary filings for company facts.')+resources.map(r=>`<article class="resource-card"><div><span class="mini-label">${r.kind}</span><h2>${r.title}</h2></div><p>${r.description}</p><a href="${r.url}" target="_blank" rel="noopener noreferrer">Open resource ↗</a></article>`).join('')+`<aside class="connection" style="margin-top:30px"><h2>Use this lab as a companion, not an authority shortcut.</h2><p>Check your course’s conventions, assignment rules, and permitted assistance. Keep the calculation, assumptions, and explanation together. External resources control their own availability and access terms; none is required to use the calculators here.</p></aside>`;
 }else{location.hash='lab';}
}
